In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Jello ")

In [4]:
world = tf.constant("world+ !")

In [5]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [7]:
with tf.Session() as sess:
    result = sess.run(hello+ world)

In [8]:
result

b'Jello world+ !'

In [9]:
a = tf.constant(10)
b = tf.constant(20)
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess: 
    result = sess.run(a+b)

In [12]:
result

30

In [13]:
fill_mat = tf.fill((4,4),10)

In [14]:
myzeros = tf.zeros((4,4))

In [15]:
myrand = tf.random_normal((4,4), mean=0, stddev=1.0)

In [16]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [17]:
my_ops = [fill_mat,myzeros,myrand,myrandu]

In [18]:
sess = tf.InteractiveSession()

In [19]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.19028687  0.47557953  1.85747659  1.65165639]
 [ 1.15520346 -0.38210088  0.19950415  0.2057198 ]
 [ 0.60638076  0.14066923  1.05227017  0.34208512]
 [ 0.57484251  0.9452216  -0.25840357 -0.93770605]]


[[ 0.09520376  0.93597412  0.79240084  0.27996612]
 [ 0.12010002  0.25871134  0.50765753  0.27796125]
 [ 0.74072051  0.34254849  0.23249054  0.95355844]
 [ 0.39477777  0.6185261   0.94443548  0.90671229]]




In [20]:
  a = tf.constant([[1,2],[3,4]])

In [21]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [23]:
b = tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [25]:
result = tf.matmul(a,b)

In [26]:
sess.run(result)

array([[210],
       [430]], dtype=int32)