In [10]:
import numpy as np

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("hello world!")

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(hello))

b'hello world!'


# Here are some notes

In [5]:
s = "string"

In [7]:
s.capitalize()

'String'

In [11]:
my_list = [1,2,3]

In [12]:
type(np.array(my_list))

numpy.ndarray

In [13]:
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3])

In [23]:
np.arange(0,10,2.1)

array([ 0. ,  2.1,  4.2,  6.3,  8.4])

In [19]:
np.zeros((5,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
np.linspace(0,11,11)

array([  0. ,   1.1,   2.2,   3.3,   4.4,   5.5,   6.6,   7.7,   8.8,
         9.9,  11. ])

In [26]:
np.random.randint(0,100,10)

array([ 3, 88, 17, 34, 91, 66, 11, 38, 26, 91])

In [30]:
arr = np.random.randint(0,100,10)

In [31]:
arr

array([20, 47,  6, 96, 56, 72, 38, 92,  7, 34])

In [32]:
arr.max()

96

In [33]:
arr.mean()

46.799999999999997

In [34]:
arr.argmax()

3

In [35]:
arr

array([20, 47,  6, 96, 56, 72, 38, 92,  7, 34])

In [36]:
arr.reshape(2,5)

array([[20, 47,  6, 96, 56],
       [72, 38, 92,  7, 34]])

In [37]:
mat = np.arange(0,100).reshape(10,10)

In [38]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
mat[4,3]

43

mat[:,0]

In [41]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [45]:
mat[mat > 50]


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])